name: workshop
toolchainRegion: us-east-1
groups:
  - name: example
    path: manifests/git/example-modules.yaml
targetAccountMappings:
  - alias: primary
    accountId:
      valueFrom:
        envVariable: PRIMARY_ACCOUNT
    default: true
    regionMappings:
      - region: us-east-1
        default: true

