version: 0.2

phases:
  build:
    commands:
      # Network
      - bash gen-reports.sh -m network/basic-cdk # needed for solutions
      # Storage
      - bash gen-reports.sh -m storage/buckets
      - bash gen-reports.sh -m storage/efs
      - bash gen-reports.sh -m storage/fsx-lustre
      - bash gen-reports.sh -m storage/opensearch # needed for solutions
      # Database
      - bash gen-reports.sh -m database/neptune
      # Orch
      - bash gen-reports.sh -m orchestration/mwaa # needed for solutions
      # Compute
      - bash gen-reports.sh -m compute/aws-batch -c 2.70.0 # needed for solutions
      # - bash gen-reports.sh -m compute/eks -c 2.51.0 # Failing currently
      - bash gen-reports.sh -m compute/emr-serverless -c 2.83.1 # needed for solutions
      # Replications
      # - bash gen-reports.sh -m replication/dockerimage-replication
  post_build:
    commands:
      - echo Build completed on `date`
artifacts:
  files:
    - '**/*'