name: local
toolchainRegion: us-east-1
groups:
  - name: example
    path: manifests/workshop/local/example-modules.yaml
targetAccountMappings:
  - alias: primary
    accountId:
      valueFrom:
        envVariable: PRIMARY_ACCOUNT
    default: true
    regionMappings:
      - region: us-east-1
        default: true

