name: buckets
path: git::https://github.com/awslabs/idf-modules.git//modules/storage/buckets/?ref=workshop-seedfarmer
parameters:
  - name: encryption-type
    value: SSE
  - name: retention-type
    value: DESTROY