name: dummy
toolchainRegion: us-east-1
groups:
  - name: dummy
    path: manifests/samples/dummy-module.yaml
  - name: dummy2
    path: manifests/samples/dummy-module.yaml
targetAccountMappings:
  - alias: primary
    accountId:
      valueFrom:
        envVariable: PRIMARY_ACCOUNT
    default: true
    parametersGlobal:
      dockerCredentialsSecret: aws-addf-docker-credentials
    regionMappings:
      - region: us-east-1
        default: true
