name: Sync GitHub with AWS CodeCommit for Scene Intelligence with Rosbag on AWS

on:
  # Triggers the workflow on push or pull request events but only for the "scene-intelligence-with-rosbag-on-aws" branch
  push:
    branches: ["scene-intelligence-with-rosbag-on-aws"]
  pull_request:
    branches: ["scene-intelligence-with-rosbag-on-aws"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Permission can be added at job level or workflow level    
permissions:
      id-token: write   # This is required for requesting the JWT
      contents: read    # This is required for actions/checkout

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Git clone the repository
        uses: actions/checkout@v3
      - name: configure aws credentials
        uses: aws-actions/configure-aws-credentials@v4.0.0
        with:
          role-to-assume: arn:aws:iam::052886665315:role/GitHubAction-AssumeRoleWithAction #change to reflect your IAM role’s ARN
          role-session-name: GitHub_to_AWS_via_FederatedOIDC
          aws-region: us-west-2
      - name: Install utilities
        run: |
          pip install git-remote-codecommit
          git clone codecommit::us-west-2://scene-intelligence-with-rosbag-on-aws
          ls -al
          ls -al scene-intelligence-with-rosbag-on-aws

          echo "Copying modules one after the other..."
          # Compute
          cp -R modules/compute/aws-batch scene-intelligence-with-rosbag-on-aws/modules/compute
          cp -R modules/compute/emr-serverless scene-intelligence-with-rosbag-on-aws/modules/compute
          # Networking
          cp -R modules/network/basic-cdk scene-intelligence-with-rosbag-on-aws/modules/network
          # Orchestration
          cp -R modules/orchestration/mwaa scene-intelligence-with-rosbag-on-aws/modules/orchestration
          # Catalog
          cp -R modules/service-catalog/app-registry scene-intelligence-with-rosbag-on-aws/modules/service-catalog
          # Storage
          cp -R modules/storage/opensearch scene-intelligence-with-rosbag-on-aws/modules/storage
          ls -al scene-intelligence-with-rosbag-on-aws/modules/
          echo "Copied modules"

          echo "Copying data folder contents..."
          cp -R data/mwaa/ scene-intelligence-with-rosbag-on-aws/data/mwaa

          cd scene-intelligence-with-rosbag-on-aws/
          git config --global user.email "ssriche@amazon.com"
          git config --global user.name "Srinivas"
          git config --global init.defaultBranch main
          git branch -a
          git add -A
          git status
          git commit -m "sync gh with cc"
          git remote -v
          git status
          git push origin main
